#!/usr/bin/env bash
#
# Generate and install udev rules that pin the robot's two USB serial adapters
# to stable names:
#
#   /dev/esp32    -> the ESP32 base controller (DiffDriveSerial)
#   /dev/ydlidar  -> the YDLidar X2
#
# Both are USB serial adapters, so whichever enumerates first becomes
# /dev/ttyUSB0 and the assignment flips across reboots. The symlinks above
# follow the hardware instead of the enumeration order.
#
# Run this ONCE, with both devices plugged in:
#
#   ./scripts/setup_udev.sh
#
# It asks which /dev/ttyUSB* is which, then picks a matching key:
#
#   * ATTRS{serial}  -- preferred. Survives being moved to another USB port.
#   * KERNELS        -- the USB port path, used when the adapters are
#                       indistinguishable (same VID:PID, no serial, which is
#                       common for CH340s and for cloned CP2102s). The device
#                       must then stay in the SAME physical port.
#
# Re-run it after swapping hardware or moving a device between ports.

set -euo pipefail

RULES_FILE=/etc/udev/rules.d/99-my-bot-serial.rules
REPO_COPY="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/udev/99-my-bot-serial.rules"

# --- collect candidate devices -----------------------------------------------

mapfile -t DEVS < <(ls /dev/ttyUSB* /dev/ttyACM* 2>/dev/null || true)

if [ "${#DEVS[@]}" -eq 0 ]; then
  echo "No /dev/ttyUSB* or /dev/ttyACM* found. Plug in the ESP32 and the lidar," >&2
  echo "then run this again." >&2
  exit 1
fi

# Walk up the sysfs tree from a tty to the USB *device* node (the one that owns
# idVendor), which is the level udev rules match on.
usb_parent() {
  local p="/sys$(udevadm info -q path -n "$1")"
  while [ "$p" != "/sys" ] && [ "$p" != "/" ]; do
    [ -f "$p/idVendor" ] && { echo "$p"; return 0; }
    p="$(dirname "$p")"
  done
  return 1
}

declare -A VID PID SER PORT
USB_DEVS=()   # only devices we could resolve; the menu numbers index THIS array
for d in "${DEVS[@]}"; do
  parent="$(usb_parent "$d")" || { echo "warn: no USB parent for $d, skipping" >&2; continue; }
  VID[$d]="$(cat "$parent/idVendor")"
  PID[$d]="$(cat "$parent/idProduct")"
  SER[$d]="$(cat "$parent/serial" 2>/dev/null || true)"
  PORT[$d]="$(basename "$parent")"
  USB_DEVS+=("$d")
done

if [ "${#USB_DEVS[@]}" -lt 2 ]; then
  echo "Found ${#USB_DEVS[@]} USB serial device(s); need both the ESP32 and the lidar" >&2
  echo "plugged in at the same time." >&2
  exit 1
fi

echo "Serial devices found:"
echo
for i in "${!USB_DEVS[@]}"; do
  d="${USB_DEVS[$i]}"
  printf "  [%d] %-14s %s:%s  serial=%-18s usb-port=%s\n" \
    "$((i + 1))" "$d" "${VID[$d]}" "${PID[$d]}" "${SER[$d]:-<none>}" "${PORT[$d]}"
done
echo

# --- ask which is which -------------------------------------------------------
#
# Autodetection is not possible here: the ESP32 and the lidar are both plain
# serial adapters with no protocol we can safely probe (poking the lidar's port
# spins its motor, poking the ESP32 resets it via DTR).

pick() {
  local prompt="$1" ans
  while true; do
    read -rp "$prompt" ans
    ans="${ans#[}"; ans="${ans%]}"
    if [[ "$ans" =~ ^[0-9]+$ ]] && [ "$ans" -ge 1 ] && [ "$ans" -le "${#USB_DEVS[@]}" ]; then
      echo "${USB_DEVS[$((ans - 1))]}"
      return 0
    fi
    echo "Enter a number between 1 and ${#USB_DEVS[@]}." >&2
  done
}

echo "Tip: unplug one device and re-run to see which entry disappears."
echo
ESP_DEV="$(pick 'Which number is the ESP32 base controller? ')"
LIDAR_DEV="$(pick 'Which number is the YDLidar? ')"

if [ "$ESP_DEV" = "$LIDAR_DEV" ]; then
  echo "Those are the same device. Aborting." >&2
  exit 1
fi

# --- choose a matching key ----------------------------------------------------

emit_rule() {
  local dev="$1" name="$2" other="$3"

  if [ -n "${SER[$dev]}" ] && [ "${SER[$dev]}" != "${SER[$other]:-}" ]; then
    printf 'SUBSYSTEM=="tty", ATTRS{idVendor}=="%s", ATTRS{idProduct}=="%s", ATTRS{serial}=="%s", SYMLINK+="%s", GROUP="dialout", MODE="0660"\n' \
      "${VID[$dev]}" "${PID[$dev]}" "${SER[$dev]}" "$name"
  else
    # No usable serial: fall back to the physical USB port path.
    printf '# %s has no unique serial -- matched by USB port. Keep it in this port.\n' "$name"
    printf 'SUBSYSTEM=="tty", SUBSYSTEMS=="usb", KERNELS=="%s", SYMLINK+="%s", GROUP="dialout", MODE="0660"\n' \
      "${PORT[$dev]}" "$name"
  fi
}

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT
{
  echo "# my_bot serial device names. Generated by scripts/setup_udev.sh on $(date -Is)."
  echo "# Regenerate after swapping hardware or moving a device to another USB port."
  echo
  emit_rule "$ESP_DEV" esp32 "$LIDAR_DEV"
  emit_rule "$LIDAR_DEV" ydlidar "$ESP_DEV"
} >"$TMP"

echo
echo "Rules to install at $RULES_FILE:"
echo
sed 's/^/    /' "$TMP"
echo

read -rp "Install? [y/N] " confirm
[[ "$confirm" =~ ^[Yy]$ ]] || { echo "Aborted, nothing written."; exit 1; }

# --- install ------------------------------------------------------------------

sudo install -m 0644 "$TMP" "$RULES_FILE"
mkdir -p "$(dirname "$REPO_COPY")"
install -m 0644 "$TMP" "$REPO_COPY"

sudo udevadm control --reload-rules
sudo udevadm trigger --subsystem-match=tty --action=add
sleep 1

echo
echo "Installed. A copy is checked in at udev/99-my-bot-serial.rules."
echo
ok=0
for name in esp32 ydlidar; do
  if [ -e "/dev/$name" ]; then
    printf '  /dev/%-8s -> %s\n' "$name" "$(readlink -f "/dev/$name")"
    ok=$((ok + 1))
  else
    printf '  /dev/%-8s MISSING\n' "$name"
  fi
done

if [ "$ok" -ne 2 ]; then
  echo
  echo "A symlink did not appear. Unplug and replug that device -- some adapters" >&2
  echo "do not re-trigger on 'udevadm trigger'. If it still does not show up:" >&2
  echo "  udevadm test \$(udevadm info -q path -n /dev/ttyUSB0)" >&2
  exit 1
fi
